import { RestrictedTermItem, PlatformPolicyItem, PseoPageData } from './types';

export const RESTRICTED_TERMS: RestrictedTermItem[] = [
  // HEALTH, MEDICAL & WEIGHT LOSS
  {
    _id: '1',
    term: 'weight loss',
    slug: 'weight-loss',
    platforms: ['all', 'tiktok', 'meta', 'google', 'youtube'],
    severity: 'critical',
    category: 'health_medical',
    riskScore: 92,
    reason: 'Triggers automated body image policies, deceptive health claims, and before-and-after ad disapprovals.',
    consequences: ['Ad rejection', 'Forced reach reduction (shadowban)', 'Demonetization'],
    safeAlternatives: ['wellness journey', 'body transformation progress', 'healthy lifestyle habits', 'fitness milestone'],
    explanation: 'TikTok and Meta aggressively throttle weight-loss terms to prevent eating disorder triggers and deceptive claims.',
    searchVolumeIndex: 98,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '2',
    term: 'fat burner',
    slug: 'fat-burner',
    platforms: ['all', 'tiktok', 'meta', 'google'],
    severity: 'critical',
    category: 'health_medical',
    riskScore: 95,
    reason: 'Classified as unproven supplement or dangerous dietary aid claim.',
    consequences: ['Instant ad ban', 'Account penalty flag'],
    safeAlternatives: ['metabolic support formula', 'active energy blend', 'fitness accelerator'],
    explanation: 'Direct dietary pill or fat-burning terminology violates FDA/FTC compliance rules on Google & Meta Ads.',
    searchVolumeIndex: 85,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '3',
    term: 'cure',
    slug: 'cure',
    platforms: ['all', 'tiktok', 'meta', 'google', 'youtube'],
    severity: 'critical',
    category: 'health_medical',
    riskScore: 99,
    reason: 'Strictly prohibited medical claim on all major ad platforms without official pharmaceutical certification.',
    consequences: ['Permanent ad account suspension', 'Content removal'],
    safeAlternatives: ['supports recovery', 'helps alleviate symptoms', 'promotes overall wellness', 'natural relief support'],
    explanation: 'Never use the word cure for any non-prescription wellness product or holistic treatment.',
    searchVolumeIndex: 90,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '4',
    term: 'before and after',
    slug: 'before-and-after',
    platforms: ['meta', 'tiktok', 'google'],
    severity: 'high',
    category: 'health_medical',
    riskScore: 88,
    reason: 'Meta Ads Policy strictly forbids before-and-after comparison imagery and copy.',
    consequences: ['Ad disapproval', 'Lower ad quality ranking'],
    safeAlternatives: ['transformation timeline', 'client evolution story', 'documented progress over 90 days'],
    explanation: 'Implies unrealistic results or generates negative self-perception.',
    searchVolumeIndex: 92,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '5',
    term: 'diet',
    slug: 'diet',
    platforms: ['all', 'tiktok', 'meta'],
    severity: 'high',
    category: 'health_medical',
    riskScore: 78,
    reason: 'TikTok algorithm heavily throttles organic video reach containing diet in captions or audio.',
    consequences: ['For You Page (FYP) shadowban', 'Age-gated suppression'],
    safeAlternatives: ['nutrition plan', 'meal protocol', 'balanced eating regimen', 'fuel strategy'],
    explanation: 'Algorithms flag diet as sensitive content under youth mental health protection policies.',
    searchVolumeIndex: 95,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '6',
    term: 'miracle pill',
    slug: 'miracle-pill',
    platforms: ['all'],
    severity: 'critical',
    category: 'health_medical',
    riskScore: 98,
    reason: 'Extreme hyperbolic health claim flagged as fraud by automated AI reviewers.',
    consequences: ['Account termination', 'Merchant account blacklisting'],
    safeAlternatives: ['targeted nutritional supplement', 'daily herbal compound'],
    explanation: 'Hyperbolic claims trigger FTC regulatory flags on all major search and social algorithms.',
    searchVolumeIndex: 70,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '7',
    term: 'botox alternative',
    slug: 'botox-alternative',
    platforms: ['meta', 'tiktok', 'google'],
    severity: 'high',
    category: 'health_medical',
    riskScore: 82,
    reason: 'Trademark violation (Botox is a registered trademark of Allergan) plus unlicensed medical comparison.',
    consequences: ['Trademark takedown', 'Ad account warning'],
    safeAlternatives: ['anti-aging smoothing serum', 'peptide wrinkle-care solution', 'collagen plumping treatment'],
    explanation: 'Using competitor medical trademarks in ad copy or scripts triggers algorithmic rejection.',
    searchVolumeIndex: 84,
    lastUpdated: '2026-10-01',
  },

  // FINANCIAL, MAKE MONEY & CRYPTO
  {
    _id: '8',
    term: 'guaranteed income',
    slug: 'guaranteed-income',
    platforms: ['all', 'meta', 'google', 'youtube', 'tiktok'],
    severity: 'critical',
    category: 'financial_guarantees',
    riskScore: 96,
    reason: 'Direct violation of FTC and platform financial deception policies (Biz-opp rules).',
    consequences: ['Immediate ad account ban', 'Video demonetization'],
    safeAlternatives: ['earning potential', 'revenue framework', 'monetization roadmap', 'skill-based income path'],
    explanation: 'No financial or business opportunity is allowed to promise guaranteed ROI or returns.',
    searchVolumeIndex: 90,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '9',
    term: 'crypto giveaway',
    slug: 'crypto-giveaway',
    platforms: ['all', 'x', 'youtube', 'tiktok', 'meta'],
    severity: 'critical',
    category: 'financial_guarantees',
    riskScore: 97,
    reason: 'High association with phishing scams, wallet draining schemes, and spam bot rings.',
    consequences: ['Instant account shadowban', 'Automated tweet suppression', 'Search ban'],
    safeAlternatives: ['community rewards program', 'ecosystem incentives', 'token distribution event'],
    explanation: 'X and YouTube automatically drop impressions by 99% for posts containing crypto giveaway.',
    searchVolumeIndex: 89,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '10',
    term: 'make $10,000/month',
    slug: 'make-10000-month',
    platforms: ['all', 'meta', 'tiktok', 'youtube', 'google'],
    severity: 'critical',
    category: 'financial_guarantees',
    riskScore: 94,
    reason: 'Unsubstantiated income claims violate ad standards and trigger consumer protection filters.',
    consequences: ['Ad account disabling', 'Limited reach on short-form videos'],
    safeAlternatives: ['scale your client roster', 'build high-value services', 'grow sustainable revenue'],
    explanation: 'Specific dollar income promises trigger high risk scores in Meta and TikTok ad moderation.',
    searchVolumeIndex: 88,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '11',
    term: 'get rich quick',
    slug: 'get-rich-quick',
    platforms: ['all'],
    severity: 'critical',
    category: 'financial_guarantees',
    riskScore: 99,
    reason: 'Direct MLM and predatory financial scheme detection keyword.',
    consequences: ['Permanent suspension', 'Content removal'],
    safeAlternatives: ['accelerated wealth building', 'long-term financial compounding', 'high-leverage business models'],
    explanation: 'Classic trigger phrase blacklisted across all automated moderation networks.',
    searchVolumeIndex: 75,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '12',
    term: 'passive income',
    slug: 'passive-income',
    platforms: ['all', 'tiktok', 'meta'],
    severity: 'moderate',
    category: 'financial_guarantees',
    riskScore: 72,
    reason: 'Heavily scrutinized under Biz-Opp guidelines, frequently flagged for review.',
    consequences: ['Lower ad delivery score', 'Manual review delays'],
    safeAlternatives: ['automated revenue stream', 'digital asset leverage', 'recurring product sales'],
    explanation: 'Overused in scam funnels, algorithms apply negative quality weights to this phrase.',
    searchVolumeIndex: 94,
    lastUpdated: '2026-10-01',
  },

  // ENGAGEMENT BAIT
  {
    _id: '13',
    term: 'giveaway',
    slug: 'giveaway',
    platforms: ['all', 'meta', 'tiktok', 'youtube'],
    severity: 'high',
    category: 'engagement_bait',
    riskScore: 84,
    reason: 'Engagement bait and lottery policy trigger. Instagram often hides posts with giveaway hashtags from Explore.',
    consequences: ['Explore page suppression', 'Restricted hashtag reach'],
    safeAlternatives: ['community celebration', 'supporter gift drop', 'exclusive reward package'],
    explanation: 'Platforms discourage artificial follower growth mechanics through giveaway tagging.',
    searchVolumeIndex: 99,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '14',
    term: 'follow for follow',
    slug: 'follow-for-follow',
    platforms: ['all', 'tiktok', 'meta', 'x'],
    severity: 'high',
    category: 'engagement_bait',
    riskScore: 86,
    reason: 'Artificial engagement manipulation rule violation.',
    consequences: ['Shadowban on hashtags', 'Account reach suppression for 14-30 days'],
    safeAlternatives: ['connect with fellow creators', 'let us network in the comments'],
    explanation: 'Explicit reciprocity baiting lowers account trust score.',
    searchVolumeIndex: 80,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '15',
    term: 'dm me for info',
    slug: 'dm-me-for-info',
    platforms: ['all', 'meta', 'tiktok'],
    severity: 'moderate',
    category: 'engagement_bait',
    riskScore: 68,
    reason: 'Funnel circumvention detection (moving users off-platform to unmoderated direct messages).',
    consequences: ['Reduced distribution in feed', 'Ad review flags'],
    safeAlternatives: ['check link in bio for full breakdown', 'full guide linked in description'],
    explanation: 'Social algorithms prefer in-app engagement or verified landing pages rather than unmonitored DMs.',
    searchVolumeIndex: 78,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '16',
    term: 'tag 3 friends',
    slug: 'tag-3-friends',
    platforms: ['all', 'meta', 'tiktok'],
    severity: 'high',
    category: 'engagement_bait',
    riskScore: 82,
    reason: 'Strictly defined as Tag Engagement Bait in Meta Quality Ranking Guidelines.',
    consequences: ['Severe reach suppression in algorithmic feed'],
    safeAlternatives: ['share this with someone who needs this insight', 'send to your marketing team'],
    explanation: 'Commanding users to tag others without intrinsic relevance degrades post ranking.',
    searchVolumeIndex: 79,
    lastUpdated: '2026-10-01',
  },

  // SENSITIVE, VIOLENCE & SPEECH CENSORSHIP
  {
    _id: '17',
    term: 'kill',
    slug: 'kill',
    platforms: ['all', 'tiktok', 'youtube', 'meta'],
    severity: 'critical',
    category: 'sensitive_violence',
    riskScore: 94,
    reason: 'Safety and violence filter trigger causing automated demonetization or video removal.',
    consequences: ['Zero FYP impressions', 'Yellow dollar sign (YouTube demonetization)'],
    safeAlternatives: ['unalive', 'take out', 'eliminate', 'destroy', 'defeat'],
    explanation: 'Creators frequently use "unalive" to evade automated speech-to-text safety filters.',
    searchVolumeIndex: 96,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '18',
    term: 'suicide',
    slug: 'suicide',
    platforms: ['all', 'tiktok', 'youtube', 'meta', 'x'],
    severity: 'critical',
    category: 'sensitive_violence',
    riskScore: 99,
    reason: 'Automated policy triggers crisis helpline modal and disables recommendation algorithm.',
    consequences: ['Complete video reach lock', 'Search query warning overlay'],
    safeAlternatives: ['self-departure', 'ending one’s own story', 'mental health crisis struggle'],
    explanation: 'Crucial for true-crime creators and documentary filmmakers who need to navigate safety filters.',
    searchVolumeIndex: 97,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '19',
    term: 'murder',
    slug: 'murder',
    platforms: ['all', 'tiktok', 'youtube'],
    severity: 'high',
    category: 'sensitive_violence',
    riskScore: 88,
    reason: 'Speech-to-text algorithm flags true crime and mystery videos for graphic violence.',
    consequences: ['Demonetization', 'Restricted mode placement'],
    safeAlternatives: ['unlawful passing', 'fatal crime incident', 'homicide case study'],
    explanation: 'Popular YouTube true crime channels use safe phrasing in title and early audio beats.',
    searchVolumeIndex: 92,
    lastUpdated: '2026-10-01',
  },
  {
    _id: '20',
    term: 'gun',
    slug: 'gun',
    platforms: ['all', 'tiktok', 'meta', 'google', 'youtube'],
    severity: 'high',
    category: 'weapons_drugs',
    riskScore: 87,
    reason: 'Regulated goods and firearms safety filter.',
    consequences: ['Ad ban', 'Video restriction for minors'],
    safeAlternatives: ['tactical gear', 'defense equipment', 'firearm accessory'],
    explanation: 'Gaming, outdoor, and news channels must phrase equipment carefully.',
    searchVolumeIndex: 85,
    lastUpdated: '2026-10-01',
  },
];

export const PLATFORM_POLICIES: PlatformPolicyItem[] = [
  {
    _id: 'p1',
    platform: 'tiktok',
    industry: 'health-supplements',
    slug: 'health-supplements',
    title: 'TikTok 2026 Health, Wellness & Supplement Ad & Video Guidelines',
    summary: 'TikTok enforces zero-tolerance on exaggerated bodily claims, rapid weight reduction promises, and before-and-after transformations. Speech-to-text algorithms proactively scan audio for blacklisted terms.',
    prohibitedPractices: [
      'Showing scale weight numbers decreasing',
      'Using terms like "fat burner", "miracle detox", or "belly fat blaster"',
      'Promising results in specific day counts (e.g. "Lose 10lbs in 7 days")',
      'Targeting weight loss products to minors under 18',
    ],
    restrictedKeywords: ['weight loss', 'fat burner', 'belly fat', 'suppressant', 'diet pill', 'detox tea'],
    requiredDisclaimers: [
      'Results may vary based on individual metabolism and consistency.',
      'Consult a physician before starting any diet or supplement routine.',
    ],
    algoSafeTips: [
      'Focus on energy, mental clarity, and daily routine rather than kilograms/pounds.',
      'Use phrases like "wellness journey", "nourishing my body", and "daily movement".',
      'Keep captions free of restrictive diet hashtags (#weightloss, #fatloss).',
    ],
    officialPolicyUrl: 'https://ads.tiktok.com/help/article/weight-management-and-body-image',
    lastReviewedYear: 2026,
  },
  {
    _id: 'p2',
    platform: 'meta',
    industry: 'ecommerce-dropshipping',
    slug: 'ecommerce-dropshipping',
    title: 'Meta Ads (Facebook & Instagram) 2026 E-commerce & Dropshipping Compliance',
    summary: 'Meta penalizes misleading product claims, unrealistic shipping guarantees, copyright infringement, and deceptive value stacking in ad copy and landing pages.',
    prohibitedPractices: [
      'Using countdown timers that reset on page refresh (Fake Urgency)',
      'Comparing product directly with branded trademarked items without authorization',
      'Stock photos claiming to be the actual manufacturing team',
      'Misleading discount percentages (e.g. "90% OFF today only" with inflated anchor prices)',
    ],
    restrictedKeywords: ['free giveaway', 'botox alternative', 'miracle cure', 'official brand partner', 'fake reviews'],
    requiredDisclaimers: [
      'Clear shipping and delivery timeframes visible above the fold.',
      'Physical business address and contact email in footer.',
    ],
    algoSafeTips: [
      'Ensure landing page speed is under 2.5 seconds on mobile.',
      'Keep ad text copy under 125 characters before the fold.',
      'Use UGC testimonials that speak to user satisfaction rather than miracle fixes.',
    ],
    officialPolicyUrl: 'https://www.facebook.com/policies_center/ads',
    lastReviewedYear: 2026,
  },
  {
    _id: 'p3',
    platform: 'youtube',
    industry: 'true-crime',
    slug: 'true-crime',
    title: 'YouTube 2026 True Crime & Sensitive Content Monetization Policy',
    summary: 'YouTube demonetizes videos (Yellow Icon) if graphic descriptions, violence terms, or tragic events are mentioned in the first 15-30 seconds or in the thumbnail/title.',
    prohibitedPractices: [
      'Using graphic words like "murder", "kill", "suicide", "blood" in the title or thumbnail',
      'Describing violent acts in graphic anatomical detail in the opening 30 seconds',
      'Monetizing recent real-world tragedies without authoritative journalistic credentials',
    ],
    restrictedKeywords: ['kill', 'murder', 'suicide', 'slaughter', 'torture', 'blood'],
    requiredDisclaimers: [
      'Content advisory disclaimer at the start of video.',
      'National mental health helpline links in description.',
    ],
    algoSafeTips: [
      'Open the video with storytelling tone: "A mysterious disappearance that shocked the town."',
      'Substitute graphic terms with "unlawful passing", "tragic loss", or "criminal investigation".',
      'Keep thumbnail imagery focused on archival photos or documents without blood or weapon overlays.',
    ],
    officialPolicyUrl: 'https://support.google.com/youtube/answer/6162278',
    lastReviewedYear: 2026,
  },
  {
    _id: 'p4',
    platform: 'meta',
    industry: 'crypto-trading',
    slug: 'crypto-trading',
    title: 'Meta & Instagram Ads 2026 Cryptocurrency & FinTech Regulatory Rules',
    summary: 'Cryptocurrency trading platforms, bots, and advisory services require prior written approval and regulatory licenses. Biz-opp and guaranteed return claims cause immediate permanent account bans.',
    prohibitedPractices: [
      'Promising daily, weekly, or annual percentage ROI',
      'Showing screenshots of crypto wallets, luxury cars, or stacks of cash',
      'Promoting Initial Coin Offerings (ICOs), binary options, or algorithmic trading bots without regulatory pre-approval',
    ],
    restrictedKeywords: ['guaranteed profit', 'crypto giveaway', 'make $10,000', 'passive crypto income', '100x gem'],
    requiredDisclaimers: [
      'Cryptocurrency trading involves substantial risk of loss and is not suitable for every investor.',
      'Past performance is not indicative of future returns.',
    ],
    algoSafeTips: [
      'Focus ad copy on security, technology architecture, and educational learning.',
      'Use phrases like "explore market insights", "blockchain infrastructure", and "portfolio diversification tools".',
    ],
    officialPolicyUrl: 'https://www.facebook.com/policies_center/ads/financial_products_services',
    lastReviewedYear: 2026,
  },
  {
    _id: 'p5',
    platform: 'google',
    industry: 'real-estate',
    slug: 'real-estate',
    title: 'Google Ads 2026 Housing & Real Estate Advertising Policy (HEC)',
    summary: 'Housing and real estate ads fall under Special Ad Category rules prohibiting targeting by demographic attributes (age, gender, parental status, postal code discrimination).',
    prohibitedPractices: [
      'Excluding specific demographics or low-income zip codes from ad distribution',
      'Unsubstantiated property investment appreciation guarantees',
      'Misleading mortgage rate advertisements without APR disclosures',
    ],
    restrictedKeywords: ['exclusive neighborhood for families', 'guaranteed rental return', 'no credit check mortgage'],
    requiredDisclaimers: [
      'Equal Housing Opportunity logo and statement on landing pages.',
      'License numbers and broker disclosures.',
    ],
    algoSafeTips: [
      'Target by broad radius (minimum 15 miles) and interest in real estate listings.',
      'Highlight architecture, amenities, and transit connectivity rather than resident demographics.',
    ],
    officialPolicyUrl: 'https://support.google.com/adspolicy/answer/9997418',
    lastReviewedYear: 2026,
  },
];

export const PSEO_PAGES: PseoPageData[] = [
  {
    keyword: 'is diet banned on tiktok ads',
    slug: 'diet',
    platform: 'tiktok',
    targetTerm: 'diet',
    titleTag: 'Is the Word "Diet" Banned on TikTok Ads? (2026 Policy & Safe Alternatives)',
    metaDescription: 'Learn why TikTok algorithm suppresses videos and ads with the word "diet", how shadowbans happen, and the 5 safe alternative phrases top creators use.',
    h1: 'Is "Diet" Banned on TikTok Ads and FYP in 2026?',
    verdict: 'High Shadowban Risk',
    explanation: 'The word "diet" is not fully banned from the English dictionary, but TikTok automated safety filters actively de-prioritize video reach containing "diet" in captions, overlays, or spoken audio to protect young users from eating disorder triggers. Paid ads using "diet" in headlines have an 82% higher rejection rate.',
    safeAlternatives: ['nutrition plan', 'healthy eating routine', 'fueling my body', 'wellness protocol'],
    policyReference: 'TikTok Community Guidelines on Body Image & Weight Management (2026 Update)',
    faqItems: [
      {
        question: 'Will my TikTok video get shadowbanned for saying "diet"?',
        answer: 'Yes, TikTok speech-to-text algorithm automatically flags "diet", "fat loss", and "calorie restriction", frequently suppressing the video from the For You Page (FYP).',
      },
      {
        question: 'What is the best alternative to "diet" on TikTok?',
        answer: 'Top fitness creators use "nutrition routine", "wellness protocol", or "meal plan" to maintain full organic distribution.',
      },
      {
        question: 'How do I test my script before posting?',
        answer: 'You can paste your entire script into the free ScriptSentinel Scanner to highlight all risky terms and replace them with safe alternatives in one click.',
      },
    ],
    searchVolume: 4200,
  },
  {
    keyword: 'is giveaway shadowbanned on instagram',
    slug: 'giveaway',
    platform: 'meta',
    targetTerm: 'giveaway',
    titleTag: 'Is the Word "Giveaway" Shadowbanned on Instagram? (2026 Algo Rules)',
    metaDescription: 'Discover why using #giveaway or asking users to tag friends kills your Instagram post reach and how to run safe promotions without account penalties.',
    h1: 'Is "Giveaway" Shadowbanned on Instagram in 2026?',
    verdict: 'High Shadowban Risk',
    explanation: 'Instagram algorithm actively de-ranks posts with #giveaway or phrases like "tag 3 friends to win" under its Engagement Bait & Artificial Distribution policy. While not a permanent ban, your post will be excluded from the Explore page and non-follower feeds.',
    safeAlternatives: ['community celebration gift', 'supporter reward drop', 'subscriber appreciation prize'],
    policyReference: 'Instagram Engagement Bait Policy & Content Quality Guidelines',
    faqItems: [
      {
        question: 'Why did my Instagram reach drop after posting a giveaway?',
        answer: 'Instagram classifies reciprocal tagging ("tag a friend") as artificial engagement bait and suppresses post distribution by up to 80%.',
      },
      {
        question: 'How can I legally run a promotion on Instagram without losing reach?',
        answer: 'Avoid using #giveaway in captions. Ask for genuine comments (e.g. "What is your biggest goal this year?") instead of forced tagging, and announce winners via stories.',
      },
    ],
    searchVolume: 5800,
  },
  {
    keyword: 'why was my facebook ad rejected for health claims',
    slug: 'weight-loss',
    platform: 'meta',
    targetTerm: 'weight loss',
    titleTag: 'Why Was My Facebook Ad Rejected for Health Claims? (Fix Guide 2026)',
    metaDescription: 'Fix your rejected Meta/Facebook health ads. Discover the exact prohibited words, before-and-after restrictions, and how to pass automated ad review.',
    h1: 'Why Was My Facebook Ad Rejected for Personal Health Claims?',
    verdict: 'Banned / Restricted',
    explanation: 'Meta strictly enforces Advertising Standards regarding Personal Attributes and Unrealistic Outcomes. Ads asserting or implying specific physical attributes, weight loss metrics, or miracle cures are automatically rejected by AI reviewers.',
    safeAlternatives: ['wellness transformation story', 'support daily vitality', 'mindful health habits'],
    policyReference: 'Meta Ads Policy 4.6 (Personal Health and Unrealistic Claims)',
    faqItems: [
      {
        question: 'Can I use before-and-after photos on Facebook ads?',
        answer: 'No. Meta prohibits side-by-side before-and-after photos or images that zoom in on specific body parts.',
      },
      {
        question: 'How do I appeal a rejected Facebook ad?',
        answer: 'Scan your ad copy and landing page with ScriptSentinel first to remove all flagged triggers, then submit a revised ad for manual review.',
      },
    ],
    searchVolume: 3600,
  },
  {
    keyword: 'youtube demonetization rules for true crime 2026',
    slug: 'murder',
    platform: 'youtube',
    targetTerm: 'murder',
    titleTag: 'YouTube True Crime Demonetization Rules 2026 (Safe Scripting Guide)',
    metaDescription: 'How true crime YouTubers avoid the dreaded Yellow Dollar Sign in 2026. Discover the 30-second rule, safe audio phrasing, and thumbnail compliance.',
    h1: 'YouTube True Crime Demonetization Rules (2026 Guide)',
    verdict: 'Context-Dependent Warning',
    explanation: 'YouTube Advertiser-Friendly Guidelines flag violent and sensitive topics based on when and how words are spoken. Speaking terms like "murder", "kill", or "blood" in the first 30 seconds of video playback will almost certainly result in yellow icon demonetization.',
    safeAlternatives: ['unlawful passing', 'fatal incident', 'disappearance investigation', 'tragic event'],
    policyReference: 'YouTube Advertiser-Friendly Content Guidelines - Violence and Sensitive Topics',
    faqItems: [
      {
        question: 'What is the YouTube 30-second rule for true crime?',
        answer: 'YouTube algorithms scrutinize the opening 30 seconds of audio and visual content. If graphic or violent terms occur here, the video is flagged for limited monetization.',
      },
      {
        question: 'Can I say "kill" or "suicide" in a documentary?',
        answer: 'Using safe alternatives like "unalive" or "self-departure" allows the automated speech analyzer to clear your video for green monetization status.',
      },
    ],
    searchVolume: 2900,
  },
];
